### ISSUE TITLE
Configlet problems on Plone 6

### ISSUE THREAD

**Issue by laulaz** [IMIO/imio.gdpr#3]
- configlet icon is broken
- description displays HTML tags :
<img width="1335" alt="Screen Shot 2022-01-06 at 12 52 05" src="https://user-images.githubusercontent.com/1101273/148378995-5e5265a1-d228-4bd1-a0e8-4288311eab54.png">

**Comment by boulch** [comment]
https://github.com/IMIO/imio.gdpr/commit/e5b3b7c6069a7fef60d5a9859aeea67778e34665
